title: すみれふの雑記帳
description: 思ったこと、考えたこと、日々のこと。
url: "https://sumire-fujimiya.github.io"
baseurl: ""

theme: minima

author: すみれふ

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
